export enum EPistePositions{
    CENTER_LINE='CENTER_LINE',
    LEFT_OF_CENTER_LINE='LEFT_OF_CENTER_LINE',
    RIGHT_OF_CENTER_LINE='RIGHT_OF_CENTER_LINE',
    BEHIND_GUARD_LINE_RIGHT ='BEHIND_GUARD_LINE_RIGHT',
    BEHIND_GUARD_LINE_LEFT ='BEHIND_GUARD_LINE_LEFT',
    NEAR_WARNING_LINE_RIGHT ='NEAR_WARNING_LINE_RIGHT',
    NEAR_WARNING_LINE_LEFT ='NEAR_WARNING_LINE_LEFT',
    WARNING_ZONE_RIGHT ='WARNING_ZONE_RIGHT',
    WARNING_ZONE_LEFT ='WARNING_ZONE_LEFT',
    BACK_LINE_RIGHT ='BACK_LINE_RIGHT',
    BACK_LINE_LEFT ='BACK_LINE_LEFT',
}