export enum EPositions{
    BOX_LEFT='BOX_LEFT',
    BOX_CENTER='BOX_CENTER',
    BOX_RIGHT='BOX_RIGHT',
    BEHIND_BOX_RIGHT='BEHIND_BOX_RIGHT',
    BEHIND_BOX_LEFT='BEHIND_BOX_LEFT',
    BACK_LINE_LEFT='BACK_LINE_LEFT',
    BACK_LINE_RIGHT='BACK_LINE_RIGHT',
}