import "../app/globals.css";

export const metadata = {
  title: 'Trekanten Video App',
  description: 'Generated by Mima',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      {children}
      </body>
    </html>
  )
}
